# ------------------- Jenkins Secret ------------------- #

apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: jenkins
  name: jenkins-certs
type: Opaque

---
# ------------------- Jenkins Service Account ------------------- #

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: jenkins
  name: jenkins

---
# ------------------- Jenkins Role & Role Binding ------------------- #

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","get","update","list","watch","patch","delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","get","update","list","watch","patch","delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
