apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      name: jenkins
      labels:
        name: jenkins
    spec:
      serviceAccountName: jenkins    
      containers:
      - name: jenkins
        image: 192.168.100.100/jenkins/jenkins:lts
        env:
        - name: JAVA_OPTS
          value: "-Duser.timezone=Asia/Shanghai"          
        ports:
        - name: web
          containerPort: 8080
        - name: agent
          containerPort: 50000
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-data
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker          
      volumes:
      - name: jenkins-data
        emptyDir: {}
      - name: docker
        hostPath: 
          path: /var/run/docker.sock        
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 8080
      targetPort: web
    - name: agent
      port: 50000
      targetPort: agent
  selector:
    name: jenkins
