- name: 安装 ipvsadm
  yum:
      state: present
      name: ipvsadm
- name: 安装 conntrack
  yum:
      state: present
      name: conntrack
      
- name: 复制 kube-proxy
  copy:
      src: /root/kubernetes/server/bin/kube-proxy
      dest: /usr/bin/
      mode: 755
- name: 复制 kube-proxy.service
  template:
          src: kube-proxy.service.j2
          dest: /usr/lib/systemd/system/kube-proxy.service

- name: 复制 proxy
  template:
          src: proxy.j2
          dest: /etc/kubernetes/proxy	  
- name: 复制 sysctl.conf
  template:
          src: sysctl.conf.j2
          dest: /etc/sysctl.conf	  
- name: 配置 iptables 代理
  shell: /usr/sbin/sysctl -p
  
- name: 复制 kube-proxy 脚本文件
  copy:
      src: proxy.sh
      dest: /tmp
      mode: 755
- name: 配置 kube-proxy
  shell: /bin/bash /tmp/proxy.sh
  
- name: 启动 kube-proxy
  service:
          name: kube-proxy
          state: started
          enabled: yes
