- name: 复制 kube-scheduler
  copy:
      src: /root/kubernetes/server/bin/kube-scheduler
      dest: /usr/bin/
      mode: 755

- name: 复制 kube-scheduler.service
  template:
          src: kube-scheduler.service.j2
          dest: /usr/lib/systemd/system/kube-scheduler.service

- name: 复制 kube-scheduler 配置文件
  template:
          src: scheduler.j2
          dest: /etc/kubernetes/scheduler

- name: 启动 kube-scheduler
  service:
          name: kube-scheduler
          state: started
          enabled: yes
